services:
  bot:
    container_name: bot
    image: air-raid-alerts
    depends_on:
      - postgres
    deploy:
      &default_deploy
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 15s
    env_file:
      - .env

  postgres:
    container_name: postgres
    image: postgres:15.2-bullseye
    deploy:
      <<: *default_deploy
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - air-raid-data:/var/lib/postgresql

volumes:
  air-raid-data:
