services:
  bot:
    build:
      context: .
    volumes:
      - .:/code
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:15.2-bullseye
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - air-raid-data:/var/lib/postgresql

volumes:
  air-raid-data:
